### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by parker1609** [CODEMCD/PS#2]

**Comment by CODEMCD** [comment]
![dag](https://user-images.githubusercontent.com/34755287/38078117-3744f3ca-3376-11e8-966f-8bc2e618b105.jpg)
![ts1](https://user-images.githubusercontent.com/34755287/38078341-eba862b6-3376-11e8-8705-b569b8e40b57.jpg)
![ts2](https://user-images.githubusercontent.com/34755287/38078343-ebd7817c-3376-11e8-95d2-4677d6413b8e.jpg)
![ts3](https://user-images.githubusercontent.com/34755287/38078344-ec06ba28-3376-11e8-9de2-1d257c8e4acd.jpg)
![ts4](https://user-images.githubusercontent.com/34755287/38078345-ec32e756-3376-11e8-9f17-2d4f580c87d7.jpg)

**Comment by CODEMCD** [comment]
![fwa](https://user-images.githubusercontent.com/34755287/38462866-6eae5022-3b28-11e8-8750-1b9ebcbc29e0.JPG)
![fwar](https://user-images.githubusercontent.com/34755287/38462970-e6b283bc-3b29-11e8-81df-62c9b863729c.JPG)

**Comment by parker1609** [comment]
Wiki 사용하지 않음.
